/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Project;

import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Frame2 extends javax.swing.JFrame {

    int count=0;
    int menu01;
    int round=10;
    public Frame2() {
        initComponents();
        ran();
    }
    
    public void ran(){
        menu01 = 1+(int)(Math.random() * (6));
        if(menu01==1){//ข้อ 1 กระดาษ น้ำเงิน ถ้าเป้น 1 เปิดแค่หน้ากระดาษ
             BluePaper.setVisible(true);   //กระดาษ ++++++
             BlueScissors.setVisible(false);  //กรรไกร น้ำเงิน
             BlueHammer.setVisible(false);  //ค้อน
             
             RedPaper.setVisible(false); //กระดาษ 
             RedScissors.setVisible(false); //กรรไกร แดง
             RedHammer.setVisible(false); //ค้อน
        }
        if(menu01==2){//ข้อ 2 กรรไกร น้ำเงิน
             BluePaper.setVisible(false);   
             BlueScissors.setVisible(true);
             BlueHammer.setVisible(false);

             RedPaper.setVisible(false);
             RedScissors.setVisible(false);
             RedHammer.setVisible(false);
        }
        if(menu01==3){//ข้อ 3 ค้อน น้ำเงิน
             BluePaper.setVisible(false);   
             BlueScissors.setVisible(false);
             BlueHammer.setVisible(true);

             RedPaper.setVisible(false);
             RedScissors.setVisible(false);
             RedHammer.setVisible(false);
        }
        
        if(menu01==4){//ข้อ 4 กระดาษ แดง
             BluePaper.setVisible(false);   
             BlueScissors.setVisible(false);
             BlueHammer.setVisible(false);

             RedPaper.setVisible(true);
             RedScissors.setVisible(false);
             RedHammer.setVisible(false);
        }
        
        if(menu01==5){//ข้อ 5 กรรไกร แดง
             BluePaper.setVisible(false);   
             BlueScissors.setVisible(false);
             BlueHammer.setVisible(false);

             RedPaper.setVisible(false);
             RedScissors.setVisible(true);
             RedHammer.setVisible(false);
        }
        
        if(menu01==6){//ข้อ 6 ค้อน แดง
             BluePaper.setVisible(false);   
             BlueScissors.setVisible(false);
             BlueHammer.setVisible(false);

             RedPaper.setVisible(false);
             RedScissors.setVisible(false);
             RedHammer.setVisible(true);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JB1 = new javax.swing.JButton();
        JB2 = new javax.swing.JButton();
        JB3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BluePaper = new javax.swing.JLabel();
        BlueScissors = new javax.swing.JLabel();
        BlueHammer = new javax.swing.JLabel();
        RedPaper = new javax.swing.JLabel();
        RedScissors = new javax.swing.JLabel();
        RedHammer = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        JL4 = new javax.swing.JLabel();
        JL5 = new javax.swing.JLabel();
        JL6 = new javax.swing.JLabel();
        JBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 600));

        JB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Untitled-4.png"))); // NOI18N
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Untitled-6.png"))); // NOI18N
        JB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB2ActionPerformed(evt);
            }
        });

        JB3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Untitled-5.png"))); // NOI18N
        JB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB3ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BluePaper.setBackground(new java.awt.Color(51, 204, 255));
        BluePaper.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        BluePaper.setForeground(new java.awt.Color(102, 204, 255));
        BluePaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BluePaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Untitled-1.png"))); // NOI18N

        BlueScissors.setBackground(new java.awt.Color(255, 255, 255));
        BlueScissors.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        BlueScissors.setForeground(new java.awt.Color(102, 204, 255));
        BlueScissors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Untitled-2.png"))); // NOI18N

        BlueHammer.setBackground(new java.awt.Color(255, 255, 255));
        BlueHammer.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        BlueHammer.setForeground(new java.awt.Color(102, 204, 255));
        BlueHammer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BlueHammer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/Untitled-3.png"))); // NOI18N

        RedPaper.setBackground(new java.awt.Color(255, 255, 255));
        RedPaper.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        RedPaper.setForeground(new java.awt.Color(102, 204, 255));
        RedPaper.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/1.png"))); // NOI18N

        RedScissors.setBackground(new java.awt.Color(255, 255, 255));
        RedScissors.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        RedScissors.setForeground(new java.awt.Color(102, 204, 255));
        RedScissors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/2.png"))); // NOI18N

        RedHammer.setBackground(new java.awt.Color(255, 255, 255));
        RedHammer.setFont(new java.awt.Font("Tahoma", 0, 120)); // NOI18N
        RedHammer.setForeground(new java.awt.Color(102, 204, 255));
        RedHammer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        RedHammer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/3.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BlueScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(BluePaper, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(32, Short.MAX_VALUE)
                    .addComponent(BlueHammer, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(11, 11, 11)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(42, Short.MAX_VALUE)
                    .addComponent(RedPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(1, 1, 1)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(52, Short.MAX_VALUE)
                    .addComponent(RedScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(RedHammer, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BlueScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(8, 8, 8)
                    .addComponent(BluePaper, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(18, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(28, Short.MAX_VALUE)
                    .addComponent(BlueHammer, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(RedPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(23, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(RedScissors, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(23, Short.MAX_VALUE)
                    .addComponent(RedHammer, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(3, 3, 3)))
        );

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hammer Paper Scissors for it");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(585, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));

        JL4.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        JL4.setForeground(new java.awt.Color(255, 255, 255));
        JL4.setText("count :");
        JL4.setToolTipText("");

        JL5.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        JL5.setForeground(new java.awt.Color(255, 255, 255));
        JL5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        JL5.setText("0");
        JL5.setToolTipText("");

        JL6.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        JL6.setForeground(new java.awt.Color(255, 255, 255));
        JL6.setText("/10");
        JL6.setToolTipText("");

        JBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JBack.setText("กลับ");
        JBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(JBack)
                .addGap(148, 148, 148)
                .addComponent(JL4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JL5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JL6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL4)
                    .addComponent(JL5)
                    .addComponent(JL6))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(JB1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JB3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(JB1)
                    .addComponent(JB2)
                    .addComponent(JB3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 717, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
        round--;
        if(round!=0){
            if(menu01==2 || menu01==4){  
                count++;
            }
        }
        else{
            if(menu01==2 || menu01==4){
                count++;
                JL5.setText(Integer.toString(count));
            }
            JOptionPane.showMessageDialog(null,"ผลคะแนนจ้า : "+count,"สนุกไหมคะ ?",JOptionPane.INFORMATION_MESSAGE);
            count=0;
            round=10;
        }
       
        JL5.setText(Integer.toString(count));
        ran();
        
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB3ActionPerformed
        //ปุ่มกรรไกร
        round--;
        if(round!=0){
            if(menu01==1 || menu01==6){ //ถ้าเป็นโจทย์กระดาษน้ำเงิน หรือ ค้อนแดง ให้บวกคะแนน 
                count++;
            }
        }
        else{
            if(menu01==1 || menu01==6){ // เช็ดรอบปุ่มสุดท้ายที่เรากด
                count++;
                JL5.setText(Integer.toString(count));
            }
                   
            JOptionPane.showMessageDialog(null,"ผลคะแนนจ้า : "+count,"สนุกไหมคะ ?",JOptionPane.INFORMATION_MESSAGE);
            count=0;
            round=10;
        }
        
        JL5.setText(Integer.toString(count));
        ran(); //เปลี่ยนโจทย์
    }//GEN-LAST:event_JB3ActionPerformed

    private void JB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB2ActionPerformed
     round--;
     if(round!=0){
        if(menu01==3 || menu01==5){
            count++;
        }
      }
      else{
            if(menu01==3 || menu01==5){
                count++;
                JL5.setText(Integer.toString(count));
            }
            JOptionPane.showMessageDialog(null,"ผลคะแนนจ้า : "+count,"สนุกไหมคะ ?",JOptionPane.INFORMATION_MESSAGE);
            count=0;
            round=10;
      }
        JL5.setText(Integer.toString(count));
        ran();
    }//GEN-LAST:event_JB2ActionPerformed

    private void JBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBackActionPerformed
        Project form1 = new Project();
        form1.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_JBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BlueHammer;
    private javax.swing.JLabel BluePaper;
    private javax.swing.JLabel BlueScissors;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JB2;
    private javax.swing.JButton JB3;
    private javax.swing.JButton JBack;
    private javax.swing.JLabel JL4;
    private javax.swing.JLabel JL5;
    private javax.swing.JLabel JL6;
    private javax.swing.JLabel RedHammer;
    private javax.swing.JLabel RedPaper;
    private javax.swing.JLabel RedScissors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
